# Copyright (c) Visly Inc.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

version: 2
jobs:
  android:
    docker:
      - image: circleci/android:api-25-alpha
    
    environment:
      _JAVA_OPTIONS: "-Xmx1500m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"

    working_directory: ~/repo/android

    steps:
      - checkout
      - run: ./gradlew androidDependencies --no-daemon --max-workers 2
      - run: ./gradlew test --no-daemon --max-workers 2

  ios:
    macos:
      xcode: "10.0.0"

    working_directory: ~/repo/ios

    steps:
      - checkout
      - run: xcodebuild test -workspace Example/VMLKit.xcworkspace -scheme VMLKit -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.0'

workflows:
  version: 2
  test_all:
    jobs:
      - android
      - ios
