[package]
name = "android"
version = "0.1.0"
authors = ["Emil Sjölander <emil@visly.app>"]
edition = "2018"
publish = false

[dependencies]
core = { path = ".." }
jni = { version = "0.5", default-features = false }

[profile.release]
lto = true

[lib]
name = "vml"
crate-type = ["cdylib"]